<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.6.4
 */

/**
 * Database `sdlab`
 */

/* `sdlab`.`data` */
$data = array(
  array('dataid' => '499','userid' => '301','locx' => '732','locy' => '1993','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:13','comment' => 'Too much water'),
  array('dataid' => '498','userid' => '239','locx' => '732','locy' => '1481','customdata' => '5','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:15','comment' => ' '),
  array('dataid' => '497','userid' => '117','locx' => '88','locy' => '1084','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:15','comment' => 'No comment '),
  array('dataid' => '496','userid' => '69','locx' => '269','locy' => '2323','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:22','comment' => ' '),
  array('dataid' => '495','userid' => '210','locx' => '767','locy' => '100','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:27','comment' => ' '),
  array('dataid' => '494','userid' => '116','locx' => '2281','locy' => '1597','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:17','comment' => 'No comment '),
  array('dataid' => '493','userid' => '266','locx' => '389','locy' => '529','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:26','comment' => ' '),
  array('dataid' => '492','userid' => '97','locx' => '1723','locy' => '2416','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '18:26','comment' => 'Too much water'),
  array('dataid' => '491','userid' => '154','locx' => '2444','locy' => '1112','customdata' => '8','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:24','comment' => ' '),
  array('dataid' => '490','userid' => '128','locx' => '1916','locy' => '1937','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:32','comment' => 'No comment '),
  array('dataid' => '489','userid' => '251','locx' => '998','locy' => '680','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:56','comment' => 'Need fix now'),
  array('dataid' => '488','userid' => '232','locx' => '199','locy' => '2173','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:60','comment' => 'Need fix now'),
  array('dataid' => '487','userid' => '109','locx' => '1191','locy' => '1980','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:29','comment' => 'Need fix now'),
  array('dataid' => '486','userid' => '309','locx' => '931','locy' => '1655','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:60','comment' => 'No comment '),
  array('dataid' => '485','userid' => '280','locx' => '1216','locy' => '35','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:20','comment' => 'No comment '),
  array('dataid' => '484','userid' => '355','locx' => '1675','locy' => '1418','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:55','comment' => 'Need fix now'),
  array('dataid' => '483','userid' => '399','locx' => '1005','locy' => '1076','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:38','comment' => 'No comment '),
  array('dataid' => '482','userid' => '287','locx' => '800','locy' => '1886','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:4','comment' => 'Need fix now'),
  array('dataid' => '481','userid' => '76','locx' => '1470','locy' => '520','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:14','comment' => ' '),
  array('dataid' => '480','userid' => '160','locx' => '82','locy' => '2267','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:35','comment' => ' '),
  array('dataid' => '479','userid' => '46','locx' => '1021','locy' => '986','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:43','comment' => ' '),
  array('dataid' => '478','userid' => '79','locx' => '198','locy' => '2429','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:6','comment' => 'Need fix now'),
  array('dataid' => '477','userid' => '122','locx' => '2196','locy' => '1106','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:53','comment' => 'Too much water'),
  array('dataid' => '476','userid' => '114','locx' => '1795','locy' => '532','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:6','comment' => ' '),
  array('dataid' => '475','userid' => '74','locx' => '2452','locy' => '1745','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:1','comment' => 'No comment '),
  array('dataid' => '474','userid' => '118','locx' => '715','locy' => '2507','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:36','comment' => 'Need fix now'),
  array('dataid' => '473','userid' => '117','locx' => '1951','locy' => '193','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:57','comment' => ' '),
  array('dataid' => '472','userid' => '72','locx' => '2197','locy' => '1972','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:60','comment' => 'Too much water'),
  array('dataid' => '471','userid' => '293','locx' => '498','locy' => '1530','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:19','comment' => 'No comment '),
  array('dataid' => '470','userid' => '276','locx' => '694','locy' => '33','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:31','comment' => ' '),
  array('dataid' => '469','userid' => '143','locx' => '2368','locy' => '22','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '17:2','comment' => 'Need fix now'),
  array('dataid' => '468','userid' => '369','locx' => '495','locy' => '1474','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '6:34','comment' => 'Need fix now'),
  array('dataid' => '467','userid' => '45','locx' => '916','locy' => '2232','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:58','comment' => 'Too much water'),
  array('dataid' => '466','userid' => '322','locx' => '1182','locy' => '1573','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '9:49','comment' => 'No comment '),
  array('dataid' => '465','userid' => '20','locx' => '252','locy' => '2128','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '22:2','comment' => 'No comment '),
  array('dataid' => '464','userid' => '191','locx' => '2485','locy' => '270','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:38','comment' => ' '),
  array('dataid' => '463','userid' => '216','locx' => '2380','locy' => '1764','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:2','comment' => 'Too much water'),
  array('dataid' => '462','userid' => '253','locx' => '746','locy' => '2065','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:31','comment' => 'Too much water'),
  array('dataid' => '461','userid' => '344','locx' => '1115','locy' => '1707','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '18:22','comment' => ' '),
  array('dataid' => '460','userid' => '139','locx' => '655','locy' => '491','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:49','comment' => 'Too much water'),
  array('dataid' => '459','userid' => '175','locx' => '1359','locy' => '1585','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '1:8','comment' => 'Need fix now'),
  array('dataid' => '458','userid' => '309','locx' => '1718','locy' => '1854','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:20','comment' => 'Need fix now'),
  array('dataid' => '457','userid' => '286','locx' => '2046','locy' => '1994','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:14','comment' => ' '),
  array('dataid' => '456','userid' => '200','locx' => '81','locy' => '668','customdata' => '21','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:18','comment' => 'Too much water'),
  array('dataid' => '455','userid' => '398','locx' => '2429','locy' => '589','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:33','comment' => 'Too much water'),
  array('dataid' => '454','userid' => '246','locx' => '2206','locy' => '1343','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:56','comment' => 'Too much water'),
  array('dataid' => '453','userid' => '201','locx' => '1974','locy' => '704','customdata' => '8','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:16','comment' => 'Need fix now'),
  array('dataid' => '452','userid' => '347','locx' => '1020','locy' => '956','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:26','comment' => 'Need fix now'),
  array('dataid' => '451','userid' => '58','locx' => '2452','locy' => '708','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:48','comment' => 'Need fix now'),
  array('dataid' => '450','userid' => '230','locx' => '2417','locy' => '2064','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:52','comment' => ' '),
  array('dataid' => '449','userid' => '152','locx' => '1123','locy' => '610','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:2','comment' => 'No comment '),
  array('dataid' => '448','userid' => '218','locx' => '400','locy' => '142','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:24','comment' => ' '),
  array('dataid' => '447','userid' => '84','locx' => '290','locy' => '648','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:26','comment' => 'No comment '),
  array('dataid' => '446','userid' => '239','locx' => '620','locy' => '1460','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:34','comment' => ' '),
  array('dataid' => '445','userid' => '317','locx' => '594','locy' => '800','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:47','comment' => 'No comment '),
  array('dataid' => '444','userid' => '51','locx' => '1871','locy' => '1270','customdata' => '4','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:15','comment' => 'Too much water'),
  array('dataid' => '443','userid' => '253','locx' => '286','locy' => '702','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:56','comment' => 'Too much water'),
  array('dataid' => '442','userid' => '333','locx' => '1480','locy' => '1846','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:44','comment' => 'Need fix now'),
  array('dataid' => '441','userid' => '351','locx' => '1911','locy' => '836','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:30','comment' => 'No comment '),
  array('dataid' => '440','userid' => '47','locx' => '176','locy' => '1785','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:30','comment' => 'Too much water'),
  array('dataid' => '439','userid' => '265','locx' => '1210','locy' => '227','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:45','comment' => 'Need fix now'),
  array('dataid' => '438','userid' => '266','locx' => '37','locy' => '1215','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:22','comment' => ' '),
  array('dataid' => '437','userid' => '241','locx' => '1466','locy' => '534','customdata' => '16','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:45','comment' => 'Too much water'),
  array('dataid' => '436','userid' => '216','locx' => '147','locy' => '643','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '26:19','comment' => 'Need fix now'),
  array('dataid' => '435','userid' => '73','locx' => '1658','locy' => '1814','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '25:2','comment' => 'Too much water'),
  array('dataid' => '434','userid' => '25','locx' => '148','locy' => '820','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:48','comment' => 'No comment '),
  array('dataid' => '433','userid' => '178','locx' => '159','locy' => '1605','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:17','comment' => ' '),
  array('dataid' => '432','userid' => '375','locx' => '2048','locy' => '522','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:42','comment' => 'Need fix now'),
  array('dataid' => '431','userid' => '52','locx' => '998','locy' => '329','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '2:20','comment' => 'Too much water'),
  array('dataid' => '430','userid' => '114','locx' => '1991','locy' => '589','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '12:32','comment' => 'Too much water'),
  array('dataid' => '429','userid' => '39','locx' => '407','locy' => '1014','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:6','comment' => 'Too much water'),
  array('dataid' => '428','userid' => '130','locx' => '1349','locy' => '1346','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:55','comment' => 'No comment '),
  array('dataid' => '427','userid' => '214','locx' => '1517','locy' => '2294','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:16','comment' => 'Need fix now'),
  array('dataid' => '426','userid' => '253','locx' => '571','locy' => '157','customdata' => '21','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:51','comment' => ' '),
  array('dataid' => '425','userid' => '181','locx' => '80','locy' => '1048','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:2','comment' => 'Too much water'),
  array('dataid' => '424','userid' => '213','locx' => '289','locy' => '286','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '16:22','comment' => 'No comment '),
  array('dataid' => '423','userid' => '107','locx' => '1472','locy' => '1912','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:16','comment' => 'Need fix now'),
  array('dataid' => '422','userid' => '368','locx' => '2342','locy' => '868','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:31','comment' => 'Need fix now'),
  array('dataid' => '421','userid' => '275','locx' => '117','locy' => '776','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:40','comment' => 'Need fix now'),
  array('dataid' => '420','userid' => '46','locx' => '1514','locy' => '993','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:31','comment' => 'Too much water'),
  array('dataid' => '419','userid' => '365','locx' => '338','locy' => '446','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:24','comment' => 'Need fix now'),
  array('dataid' => '418','userid' => '317','locx' => '1518','locy' => '2051','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:41','comment' => ' '),
  array('dataid' => '417','userid' => '319','locx' => '1795','locy' => '1210','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:6','comment' => 'No comment '),
  array('dataid' => '416','userid' => '350','locx' => '1354','locy' => '246','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:14','comment' => 'No comment '),
  array('dataid' => '415','userid' => '316','locx' => '1919','locy' => '351','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:35','comment' => 'Need fix now'),
  array('dataid' => '414','userid' => '214','locx' => '685','locy' => '1046','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:19','comment' => 'Too much water'),
  array('dataid' => '413','userid' => '207','locx' => '1119','locy' => '1434','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:60','comment' => ' '),
  array('dataid' => '412','userid' => '254','locx' => '2305','locy' => '752','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '21:48','comment' => 'Need fix now'),
  array('dataid' => '411','userid' => '29','locx' => '1094','locy' => '602','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:36','comment' => 'Too much water'),
  array('dataid' => '410','userid' => '291','locx' => '2207','locy' => '15','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:60','comment' => ' '),
  array('dataid' => '409','userid' => '138','locx' => '1132','locy' => '1063','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:11','comment' => ' '),
  array('dataid' => '408','userid' => '63','locx' => '302','locy' => '1514','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:14','comment' => 'Too much water'),
  array('dataid' => '407','userid' => '150','locx' => '1388','locy' => '2296','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:16','comment' => 'Too much water'),
  array('dataid' => '406','userid' => '375','locx' => '2345','locy' => '1673','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:18','comment' => 'No comment '),
  array('dataid' => '405','userid' => '88','locx' => '2379','locy' => '1093','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '11:21','comment' => 'Too much water'),
  array('dataid' => '404','userid' => '38','locx' => '1720','locy' => '1978','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:13','comment' => 'No comment '),
  array('dataid' => '403','userid' => '265','locx' => '361','locy' => '1139','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:41','comment' => 'Too much water'),
  array('dataid' => '402','userid' => '14','locx' => '314','locy' => '747','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:13','comment' => ' '),
  array('dataid' => '401','userid' => '200','locx' => '2498','locy' => '225','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:41','comment' => 'Need fix now'),
  array('dataid' => '400','userid' => '54','locx' => '2387','locy' => '140','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:43','comment' => 'No comment '),
  array('dataid' => '399','userid' => '287','locx' => '845','locy' => '200','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:6','comment' => ' '),
  array('dataid' => '398','userid' => '266','locx' => '1779','locy' => '2219','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '10:46','comment' => 'No comment '),
  array('dataid' => '397','userid' => '32','locx' => '2229','locy' => '687','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:46','comment' => 'Need fix now'),
  array('dataid' => '396','userid' => '46','locx' => '138','locy' => '1989','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '18:21','comment' => 'Need fix now'),
  array('dataid' => '395','userid' => '22','locx' => '1066','locy' => '336','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:49','comment' => 'No comment '),
  array('dataid' => '394','userid' => '239','locx' => '426','locy' => '1726','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:26','comment' => 'Too much water'),
  array('dataid' => '393','userid' => '202','locx' => '1595','locy' => '162','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:12','comment' => 'Too much water'),
  array('dataid' => '392','userid' => '278','locx' => '622','locy' => '132','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:37','comment' => 'Need fix now'),
  array('dataid' => '391','userid' => '333','locx' => '2499','locy' => '768','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:31','comment' => 'Need fix now'),
  array('dataid' => '390','userid' => '269','locx' => '1427','locy' => '1237','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:7','comment' => ' '),
  array('dataid' => '389','userid' => '28','locx' => '2088','locy' => '2459','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:46','comment' => 'Too much water'),
  array('dataid' => '388','userid' => '245','locx' => '916','locy' => '2020','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:21','comment' => 'No comment '),
  array('dataid' => '387','userid' => '351','locx' => '1166','locy' => '355','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:39','comment' => ' '),
  array('dataid' => '386','userid' => '124','locx' => '1667','locy' => '2157','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '13:3','comment' => 'No comment '),
  array('dataid' => '385','userid' => '72','locx' => '598','locy' => '2255','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:27','comment' => 'Need fix now'),
  array('dataid' => '384','userid' => '53','locx' => '1728','locy' => '1875','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '3:52','comment' => 'No comment '),
  array('dataid' => '383','userid' => '175','locx' => '1309','locy' => '2400','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:50','comment' => 'No comment '),
  array('dataid' => '382','userid' => '94','locx' => '1614','locy' => '494','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:52','comment' => 'Need fix now'),
  array('dataid' => '381','userid' => '70','locx' => '37','locy' => '658','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:52','comment' => 'Need fix now'),
  array('dataid' => '380','userid' => '138','locx' => '1594','locy' => '2262','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '18:29','comment' => 'Too much water'),
  array('dataid' => '379','userid' => '291','locx' => '1547','locy' => '1824','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:20','comment' => 'Need fix now'),
  array('dataid' => '378','userid' => '96','locx' => '684','locy' => '994','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:35','comment' => ' '),
  array('dataid' => '377','userid' => '319','locx' => '1651','locy' => '1306','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:5','comment' => 'Too much water'),
  array('dataid' => '376','userid' => '143','locx' => '809','locy' => '2454','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:29','comment' => 'Too much water'),
  array('dataid' => '375','userid' => '388','locx' => '2501','locy' => '676','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '3:54','comment' => ' '),
  array('dataid' => '374','userid' => '129','locx' => '81','locy' => '1896','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:37','comment' => ' '),
  array('dataid' => '373','userid' => '27','locx' => '1133','locy' => '1863','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:47','comment' => 'Need fix now'),
  array('dataid' => '372','userid' => '51','locx' => '1521','locy' => '1935','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:9','comment' => 'Need fix now'),
  array('dataid' => '371','userid' => '4','locx' => '131','locy' => '202','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:38','comment' => ' '),
  array('dataid' => '370','userid' => '135','locx' => '2197','locy' => '2150','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:6','comment' => ' '),
  array('dataid' => '369','userid' => '204','locx' => '1035','locy' => '723','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:56','comment' => ' '),
  array('dataid' => '368','userid' => '51','locx' => '1837','locy' => '923','customdata' => '3','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:53','comment' => 'Need fix now'),
  array('dataid' => '367','userid' => '48','locx' => '1532','locy' => '421','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:19','comment' => 'No comment '),
  array('dataid' => '366','userid' => '287','locx' => '2322','locy' => '2128','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:60','comment' => ' '),
  array('dataid' => '365','userid' => '299','locx' => '1314','locy' => '1016','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:36','comment' => ' '),
  array('dataid' => '364','userid' => '344','locx' => '2413','locy' => '552','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:6','comment' => ' '),
  array('dataid' => '363','userid' => '360','locx' => '196','locy' => '1599','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:51','comment' => 'No comment '),
  array('dataid' => '362','userid' => '68','locx' => '1603','locy' => '445','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:43','comment' => 'Need fix now'),
  array('dataid' => '361','userid' => '228','locx' => '1936','locy' => '916','customdata' => '21','custommode' => 'inch','approximatedata' => '1 feet','time' => '14:9','comment' => 'Too much water'),
  array('dataid' => '360','userid' => '131','locx' => '521','locy' => '389','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:54','comment' => 'Need fix now'),
  array('dataid' => '359','userid' => '396','locx' => '2037','locy' => '2147','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:34','comment' => 'Need fix now'),
  array('dataid' => '358','userid' => '307','locx' => '1266','locy' => '2420','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '13:22','comment' => ' '),
  array('dataid' => '357','userid' => '286','locx' => '1795','locy' => '1910','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:14','comment' => 'Too much water'),
  array('dataid' => '356','userid' => '279','locx' => '779','locy' => '1725','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:45','comment' => 'No comment '),
  array('dataid' => '355','userid' => '57','locx' => '175','locy' => '1791','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '9:49','comment' => ' '),
  array('dataid' => '354','userid' => '109','locx' => '333','locy' => '1163','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:58','comment' => 'No comment '),
  array('dataid' => '353','userid' => '93','locx' => '189','locy' => '87','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:16','comment' => 'Too much water'),
  array('dataid' => '352','userid' => '214','locx' => '1373','locy' => '138','customdata' => '21','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:55','comment' => 'Need fix now'),
  array('dataid' => '351','userid' => '181','locx' => '1748','locy' => '2311','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:22','comment' => ' '),
  array('dataid' => '350','userid' => '205','locx' => '1609','locy' => '842','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '14:16','comment' => 'Need fix now'),
  array('dataid' => '349','userid' => '251','locx' => '1974','locy' => '67','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '21:11','comment' => 'No comment '),
  array('dataid' => '348','userid' => '63','locx' => '1758','locy' => '1549','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:53','comment' => ' '),
  array('dataid' => '347','userid' => '135','locx' => '1780','locy' => '2462','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '20:21','comment' => 'Need fix now'),
  array('dataid' => '346','userid' => '44','locx' => '2263','locy' => '803','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:9','comment' => ' '),
  array('dataid' => '345','userid' => '212','locx' => '1047','locy' => '633','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:10','comment' => 'Too much water'),
  array('dataid' => '344','userid' => '136','locx' => '110','locy' => '910','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:35','comment' => ' '),
  array('dataid' => '343','userid' => '378','locx' => '1137','locy' => '2143','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '17:8','comment' => 'Need fix now'),
  array('dataid' => '342','userid' => '225','locx' => '1891','locy' => '1956','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '9:49','comment' => ' '),
  array('dataid' => '341','userid' => '65','locx' => '1215','locy' => '2223','customdata' => '5','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:34','comment' => 'Need fix now'),
  array('dataid' => '340','userid' => '215','locx' => '1079','locy' => '1130','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:23','comment' => 'Need fix now'),
  array('dataid' => '339','userid' => '387','locx' => '306','locy' => '1720','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '13:50','comment' => 'Need fix now'),
  array('dataid' => '338','userid' => '93','locx' => '1107','locy' => '2061','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:33','comment' => 'No comment '),
  array('dataid' => '337','userid' => '295','locx' => '353','locy' => '1703','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:21','comment' => 'Too much water'),
  array('dataid' => '336','userid' => '54','locx' => '1143','locy' => '1019','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:35','comment' => 'No comment '),
  array('dataid' => '335','userid' => '384','locx' => '1989','locy' => '1907','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '13:10','comment' => 'Need fix now'),
  array('dataid' => '334','userid' => '183','locx' => '2280','locy' => '339','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:49','comment' => 'Need fix now'),
  array('dataid' => '333','userid' => '289','locx' => '481','locy' => '438','customdata' => '8','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:22','comment' => 'No comment '),
  array('dataid' => '332','userid' => '55','locx' => '2359','locy' => '2364','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:55','comment' => 'No comment '),
  array('dataid' => '331','userid' => '259','locx' => '1489','locy' => '226','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:54','comment' => 'Need fix now'),
  array('dataid' => '330','userid' => '260','locx' => '2254','locy' => '898','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:40','comment' => ' '),
  array('dataid' => '329','userid' => '187','locx' => '1185','locy' => '1830','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:19','comment' => ' '),
  array('dataid' => '328','userid' => '372','locx' => '2102','locy' => '2321','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '2:54','comment' => 'Need fix now'),
  array('dataid' => '327','userid' => '239','locx' => '1197','locy' => '681','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:5','comment' => ' '),
  array('dataid' => '326','userid' => '282','locx' => '377','locy' => '395','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:58','comment' => 'Need fix now'),
  array('dataid' => '325','userid' => '304','locx' => '2038','locy' => '1463','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:42','comment' => ' '),
  array('dataid' => '324','userid' => '396','locx' => '910','locy' => '1689','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:55','comment' => ' '),
  array('dataid' => '323','userid' => '131','locx' => '1342','locy' => '2133','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '14:22','comment' => ' '),
  array('dataid' => '322','userid' => '119','locx' => '1474','locy' => '1584','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:2','comment' => ' '),
  array('dataid' => '321','userid' => '309','locx' => '2071','locy' => '573','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:9','comment' => ' '),
  array('dataid' => '320','userid' => '186','locx' => '1389','locy' => '953','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:2','comment' => 'Too much water'),
  array('dataid' => '319','userid' => '213','locx' => '1376','locy' => '2203','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:41','comment' => 'Too much water'),
  array('dataid' => '318','userid' => '172','locx' => '324','locy' => '1636','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:41','comment' => 'Need fix now'),
  array('dataid' => '317','userid' => '231','locx' => '1517','locy' => '473','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:54','comment' => 'Too much water'),
  array('dataid' => '316','userid' => '70','locx' => '1108','locy' => '1824','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:8','comment' => 'Need fix now'),
  array('dataid' => '315','userid' => '32','locx' => '664','locy' => '476','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '19:40','comment' => 'Too much water'),
  array('dataid' => '314','userid' => '46','locx' => '396','locy' => '1697','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:58','comment' => 'Too much water'),
  array('dataid' => '313','userid' => '354','locx' => '749','locy' => '676','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:1','comment' => ' '),
  array('dataid' => '312','userid' => '288','locx' => '1524','locy' => '2033','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:47','comment' => 'Need fix now'),
  array('dataid' => '311','userid' => '272','locx' => '1772','locy' => '1419','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '21:41','comment' => ' '),
  array('dataid' => '310','userid' => '95','locx' => '902','locy' => '80','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '25:8','comment' => ' '),
  array('dataid' => '309','userid' => '308','locx' => '542','locy' => '771','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:30','comment' => 'No comment '),
  array('dataid' => '308','userid' => '267','locx' => '982','locy' => '412','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:54','comment' => 'Too much water'),
  array('dataid' => '307','userid' => '13','locx' => '1999','locy' => '2468','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '23:34','comment' => 'No comment '),
  array('dataid' => '306','userid' => '8','locx' => '1261','locy' => '1248','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:48','comment' => 'No comment '),
  array('dataid' => '305','userid' => '162','locx' => '573','locy' => '2101','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:57','comment' => ' '),
  array('dataid' => '304','userid' => '344','locx' => '152','locy' => '1352','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '10:1','comment' => 'No comment '),
  array('dataid' => '303','userid' => '134','locx' => '2066','locy' => '1019','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:22','comment' => 'No comment '),
  array('dataid' => '302','userid' => '203','locx' => '64','locy' => '1998','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:23','comment' => 'Need fix now'),
  array('dataid' => '301','userid' => '40','locx' => '818','locy' => '2142','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:48','comment' => ' '),
  array('dataid' => '300','userid' => '291','locx' => '1612','locy' => '2448','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:39','comment' => 'Too much water'),
  array('dataid' => '299','userid' => '128','locx' => '107','locy' => '1386','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:49','comment' => 'Need fix now'),
  array('dataid' => '298','userid' => '87','locx' => '595','locy' => '244','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:59','comment' => 'Too much water'),
  array('dataid' => '297','userid' => '391','locx' => '777','locy' => '417','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:45','comment' => 'No comment '),
  array('dataid' => '296','userid' => '194','locx' => '2388','locy' => '1933','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:45','comment' => 'No comment '),
  array('dataid' => '295','userid' => '63','locx' => '2284','locy' => '643','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:51','comment' => 'No comment '),
  array('dataid' => '294','userid' => '28','locx' => '962','locy' => '103','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:29','comment' => 'Too much water'),
  array('dataid' => '293','userid' => '137','locx' => '582','locy' => '439','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:36','comment' => 'Too much water'),
  array('dataid' => '292','userid' => '92','locx' => '178','locy' => '687','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:2','comment' => ' '),
  array('dataid' => '291','userid' => '260','locx' => '147','locy' => '2017','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:5','comment' => ' '),
  array('dataid' => '290','userid' => '49','locx' => '991','locy' => '210','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:43','comment' => 'Too much water'),
  array('dataid' => '289','userid' => '264','locx' => '2488','locy' => '449','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:47','comment' => 'Too much water'),
  array('dataid' => '288','userid' => '279','locx' => '1713','locy' => '787','customdata' => '4','custommode' => 'inch','approximatedata' => '1 feet','time' => '11:22','comment' => 'Too much water'),
  array('dataid' => '287','userid' => '39','locx' => '685','locy' => '1872','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:21','comment' => 'Too much water'),
  array('dataid' => '286','userid' => '195','locx' => '1625','locy' => '849','customdata' => '21','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:6','comment' => 'Too much water'),
  array('dataid' => '285','userid' => '48','locx' => '2415','locy' => '2172','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:40','comment' => ' '),
  array('dataid' => '284','userid' => '374','locx' => '945','locy' => '2155','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:59','comment' => 'Need fix now'),
  array('dataid' => '283','userid' => '391','locx' => '1344','locy' => '1011','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:35','comment' => 'Too much water'),
  array('dataid' => '282','userid' => '335','locx' => '831','locy' => '1365','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:54','comment' => 'Too much water'),
  array('dataid' => '281','userid' => '66','locx' => '1656','locy' => '899','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '16:26','comment' => 'Need fix now'),
  array('dataid' => '280','userid' => '273','locx' => '512','locy' => '1787','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:26','comment' => 'Too much water'),
  array('dataid' => '279','userid' => '287','locx' => '697','locy' => '93','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:51','comment' => 'Too much water'),
  array('dataid' => '278','userid' => '242','locx' => '1422','locy' => '1850','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:16','comment' => 'No comment '),
  array('dataid' => '277','userid' => '27','locx' => '1457','locy' => '50','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:36','comment' => 'Need fix now'),
  array('dataid' => '276','userid' => '390','locx' => '609','locy' => '1484','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:59','comment' => 'No comment '),
  array('dataid' => '275','userid' => '91','locx' => '58','locy' => '2479','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:15','comment' => 'Too much water'),
  array('dataid' => '274','userid' => '224','locx' => '1403','locy' => '1714','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '14:9','comment' => ' '),
  array('dataid' => '273','userid' => '35','locx' => '133','locy' => '1453','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:2','comment' => 'Too much water'),
  array('dataid' => '272','userid' => '399','locx' => '1657','locy' => '1159','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:36','comment' => ' '),
  array('dataid' => '271','userid' => '299','locx' => '1200','locy' => '721','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '21:48','comment' => ' '),
  array('dataid' => '270','userid' => '194','locx' => '269','locy' => '403','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:13','comment' => ' '),
  array('dataid' => '269','userid' => '266','locx' => '1770','locy' => '762','customdata' => '8','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:36','comment' => 'Need fix now'),
  array('dataid' => '268','userid' => '277','locx' => '1671','locy' => '256','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:19','comment' => ' '),
  array('dataid' => '267','userid' => '215','locx' => '1908','locy' => '1270','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:42','comment' => 'Too much water'),
  array('dataid' => '266','userid' => '341','locx' => '710','locy' => '540','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:26','comment' => 'Need fix now'),
  array('dataid' => '265','userid' => '400','locx' => '185','locy' => '591','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:28','comment' => 'Need fix now'),
  array('dataid' => '264','userid' => '84','locx' => '275','locy' => '2111','customdata' => '12','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:58','comment' => 'No comment '),
  array('dataid' => '263','userid' => '260','locx' => '1650','locy' => '1213','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:22','comment' => ' '),
  array('dataid' => '262','userid' => '352','locx' => '2471','locy' => '800','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '26:58','comment' => 'No comment '),
  array('dataid' => '261','userid' => '275','locx' => '1850','locy' => '143','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:11','comment' => ' '),
  array('dataid' => '260','userid' => '272','locx' => '438','locy' => '2191','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '13:18','comment' => ' '),
  array('dataid' => '259','userid' => '373','locx' => '538','locy' => '1141','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:31','comment' => ' '),
  array('dataid' => '258','userid' => '20','locx' => '1277','locy' => '1759','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '16:33','comment' => 'Need fix now'),
  array('dataid' => '257','userid' => '318','locx' => '1532','locy' => '1783','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:29','comment' => 'Need fix now'),
  array('dataid' => '256','userid' => '103','locx' => '2189','locy' => '1645','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:43','comment' => 'Need fix now'),
  array('dataid' => '255','userid' => '21','locx' => '1090','locy' => '487','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '3:39','comment' => 'Need fix now'),
  array('dataid' => '254','userid' => '41','locx' => '1098','locy' => '1573','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '23:43','comment' => ' '),
  array('dataid' => '253','userid' => '80','locx' => '879','locy' => '1908','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:53','comment' => 'Need fix now'),
  array('dataid' => '252','userid' => '71','locx' => '1628','locy' => '1575','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:34','comment' => ' '),
  array('dataid' => '251','userid' => '131','locx' => '164','locy' => '1039','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:10','comment' => 'No comment '),
  array('dataid' => '250','userid' => '263','locx' => '720','locy' => '71','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:25','comment' => 'No comment '),
  array('dataid' => '249','userid' => '346','locx' => '1552','locy' => '1367','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:30','comment' => 'Too much water'),
  array('dataid' => '248','userid' => '195','locx' => '1905','locy' => '1145','customdata' => '21','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:3','comment' => 'Need fix now'),
  array('dataid' => '247','userid' => '191','locx' => '2362','locy' => '2168','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:44','comment' => 'Need fix now'),
  array('dataid' => '246','userid' => '339','locx' => '2243','locy' => '732','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:31','comment' => ' '),
  array('dataid' => '245','userid' => '94','locx' => '464','locy' => '2088','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '22:14','comment' => 'Need fix now'),
  array('dataid' => '244','userid' => '176','locx' => '2329','locy' => '1282','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:54','comment' => 'Too much water'),
  array('dataid' => '243','userid' => '4','locx' => '566','locy' => '41','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '11:52','comment' => 'Need fix now'),
  array('dataid' => '242','userid' => '332','locx' => '1146','locy' => '1968','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:46','comment' => ' '),
  array('dataid' => '241','userid' => '4','locx' => '512','locy' => '2127','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:7','comment' => 'Need fix now'),
  array('dataid' => '240','userid' => '390','locx' => '321','locy' => '755','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:48','comment' => ' '),
  array('dataid' => '239','userid' => '167','locx' => '1715','locy' => '1384','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:36','comment' => 'Too much water'),
  array('dataid' => '238','userid' => '278','locx' => '1700','locy' => '672','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:31','comment' => 'No comment '),
  array('dataid' => '237','userid' => '238','locx' => '512','locy' => '151','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:52','comment' => 'Too much water'),
  array('dataid' => '236','userid' => '244','locx' => '1488','locy' => '1901','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:55','comment' => ' '),
  array('dataid' => '235','userid' => '239','locx' => '2025','locy' => '131','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:3','comment' => ' '),
  array('dataid' => '234','userid' => '69','locx' => '2015','locy' => '1686','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:20','comment' => ' '),
  array('dataid' => '233','userid' => '254','locx' => '2199','locy' => '797','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:14','comment' => ' '),
  array('dataid' => '232','userid' => '291','locx' => '1800','locy' => '486','customdata' => '16','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:50','comment' => ' '),
  array('dataid' => '231','userid' => '308','locx' => '1303','locy' => '942','customdata' => '6','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:56','comment' => ' '),
  array('dataid' => '230','userid' => '157','locx' => '538','locy' => '2129','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '26:52','comment' => 'No comment '),
  array('dataid' => '229','userid' => '37','locx' => '2194','locy' => '289','customdata' => '7','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:28','comment' => 'No comment '),
  array('dataid' => '228','userid' => '383','locx' => '2071','locy' => '1066','customdata' => '21','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:56','comment' => 'Too much water'),
  array('dataid' => '227','userid' => '173','locx' => '734','locy' => '1918','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:1','comment' => 'Need fix now'),
  array('dataid' => '226','userid' => '136','locx' => '1126','locy' => '760','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '13:4','comment' => 'Need fix now'),
  array('dataid' => '225','userid' => '47','locx' => '2340','locy' => '2243','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:31','comment' => 'No comment '),
  array('dataid' => '224','userid' => '226','locx' => '2300','locy' => '1349','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '9:4','comment' => 'No comment '),
  array('dataid' => '223','userid' => '308','locx' => '289','locy' => '2392','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '19:43','comment' => 'Too much water'),
  array('dataid' => '222','userid' => '216','locx' => '505','locy' => '1751','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:52','comment' => 'Need fix now'),
  array('dataid' => '221','userid' => '366','locx' => '2281','locy' => '373','customdata' => '3','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:42','comment' => 'Need fix now'),
  array('dataid' => '220','userid' => '2','locx' => '1774','locy' => '1311','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:45','comment' => 'Too much water'),
  array('dataid' => '219','userid' => '45','locx' => '508','locy' => '1055','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:19','comment' => 'Too much water'),
  array('dataid' => '218','userid' => '270','locx' => '1475','locy' => '1011','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:28','comment' => 'No comment '),
  array('dataid' => '217','userid' => '180','locx' => '997','locy' => '2206','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:36','comment' => 'Need fix now'),
  array('dataid' => '216','userid' => '380','locx' => '980','locy' => '193','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '10:59','comment' => ' '),
  array('dataid' => '215','userid' => '311','locx' => '1333','locy' => '1550','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:9','comment' => 'No comment '),
  array('dataid' => '214','userid' => '395','locx' => '1374','locy' => '2279','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:48','comment' => 'Too much water'),
  array('dataid' => '213','userid' => '245','locx' => '1263','locy' => '93','customdata' => '5','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:19','comment' => 'Too much water'),
  array('dataid' => '212','userid' => '34','locx' => '2301','locy' => '1171','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '13:54','comment' => 'Need fix now'),
  array('dataid' => '211','userid' => '241','locx' => '845','locy' => '269','customdata' => '21','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:24','comment' => 'No comment '),
  array('dataid' => '210','userid' => '118','locx' => '432','locy' => '2022','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:9','comment' => 'Need fix now'),
  array('dataid' => '209','userid' => '363','locx' => '1235','locy' => '1019','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:56','comment' => 'No comment '),
  array('dataid' => '208','userid' => '82','locx' => '717','locy' => '465','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:9','comment' => 'Too much water'),
  array('dataid' => '207','userid' => '81','locx' => '250','locy' => '1056','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '22:18','comment' => 'Too much water'),
  array('dataid' => '206','userid' => '141','locx' => '1846','locy' => '807','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:1','comment' => 'No comment '),
  array('dataid' => '205','userid' => '363','locx' => '612','locy' => '342','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:56','comment' => 'Too much water'),
  array('dataid' => '204','userid' => '72','locx' => '1845','locy' => '690','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '22:26','comment' => 'Too much water'),
  array('dataid' => '203','userid' => '96','locx' => '1289','locy' => '673','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:37','comment' => 'Too much water'),
  array('dataid' => '202','userid' => '369','locx' => '1223','locy' => '978','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:20','comment' => 'No comment '),
  array('dataid' => '201','userid' => '281','locx' => '2382','locy' => '616','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:34','comment' => ' '),
  array('dataid' => '200','userid' => '326','locx' => '675','locy' => '763','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:16','comment' => 'No comment '),
  array('dataid' => '199','userid' => '218','locx' => '603','locy' => '1594','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:34','comment' => ' '),
  array('dataid' => '198','userid' => '156','locx' => '10','locy' => '552','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:29','comment' => 'No comment '),
  array('dataid' => '197','userid' => '7','locx' => '2395','locy' => '347','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:18','comment' => 'No comment '),
  array('dataid' => '196','userid' => '353','locx' => '2017','locy' => '1870','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '21:32','comment' => 'No comment '),
  array('dataid' => '195','userid' => '68','locx' => '2425','locy' => '1095','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:12','comment' => 'Need fix now'),
  array('dataid' => '194','userid' => '21','locx' => '1900','locy' => '209','customdata' => '12','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:60','comment' => 'No comment '),
  array('dataid' => '193','userid' => '307','locx' => '1627','locy' => '1525','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:49','comment' => 'Need fix now'),
  array('dataid' => '192','userid' => '110','locx' => '1707','locy' => '1030','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:29','comment' => 'Need fix now'),
  array('dataid' => '191','userid' => '207','locx' => '2168','locy' => '1303','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:29','comment' => 'Too much water'),
  array('dataid' => '190','userid' => '390','locx' => '1900','locy' => '1681','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:33','comment' => ' '),
  array('dataid' => '189','userid' => '113','locx' => '1153','locy' => '2475','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:22','comment' => ' '),
  array('dataid' => '188','userid' => '382','locx' => '755','locy' => '1483','customdata' => '9','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:54','comment' => 'Need fix now'),
  array('dataid' => '187','userid' => '364','locx' => '1460','locy' => '2311','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:36','comment' => 'No comment '),
  array('dataid' => '186','userid' => '348','locx' => '645','locy' => '1653','customdata' => '2','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:33','comment' => 'Need fix now'),
  array('dataid' => '185','userid' => '199','locx' => '828','locy' => '1645','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:40','comment' => 'Need fix now'),
  array('dataid' => '184','userid' => '22','locx' => '2116','locy' => '1262','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:2','comment' => 'Too much water'),
  array('dataid' => '183','userid' => '32','locx' => '1763','locy' => '1787','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:2','comment' => 'No comment '),
  array('dataid' => '182','userid' => '256','locx' => '769','locy' => '199','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '3:27','comment' => 'Too much water'),
  array('dataid' => '181','userid' => '248','locx' => '1715','locy' => '1489','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '13:32','comment' => 'Too much water'),
  array('dataid' => '180','userid' => '211','locx' => '2442','locy' => '1406','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '1:23','comment' => ' '),
  array('dataid' => '179','userid' => '266','locx' => '2485','locy' => '999','customdata' => '16','custommode' => 'inch','approximatedata' => '3 feet','time' => '14:34','comment' => ' '),
  array('dataid' => '178','userid' => '212','locx' => '1771','locy' => '88','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:41','comment' => 'Need fix now'),
  array('dataid' => '177','userid' => '98','locx' => '672','locy' => '1965','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:1','comment' => 'No comment '),
  array('dataid' => '176','userid' => '237','locx' => '2325','locy' => '1959','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:13','comment' => 'Need fix now'),
  array('dataid' => '175','userid' => '113','locx' => '2139','locy' => '2426','customdata' => '8','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:50','comment' => ' '),
  array('dataid' => '174','userid' => '145','locx' => '983','locy' => '1432','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '10:7','comment' => 'No comment '),
  array('dataid' => '173','userid' => '315','locx' => '603','locy' => '1118','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:50','comment' => ' '),
  array('dataid' => '172','userid' => '154','locx' => '1239','locy' => '1591','customdata' => '21','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:17','comment' => 'No comment '),
  array('dataid' => '171','userid' => '259','locx' => '2306','locy' => '2426','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '13:20','comment' => ' '),
  array('dataid' => '170','userid' => '159','locx' => '1180','locy' => '251','customdata' => '7','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:44','comment' => ' '),
  array('dataid' => '169','userid' => '185','locx' => '146','locy' => '2190','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:48','comment' => 'Need fix now'),
  array('dataid' => '168','userid' => '261','locx' => '251','locy' => '2464','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '3:17','comment' => ' '),
  array('dataid' => '167','userid' => '284','locx' => '1529','locy' => '1271','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:24','comment' => 'Too much water'),
  array('dataid' => '166','userid' => '197','locx' => '218','locy' => '1487','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:28','comment' => ' '),
  array('dataid' => '165','userid' => '273','locx' => '428','locy' => '1499','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:25','comment' => ' '),
  array('dataid' => '164','userid' => '191','locx' => '203','locy' => '1630','customdata' => '4','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:17','comment' => ' '),
  array('dataid' => '163','userid' => '180','locx' => '1301','locy' => '902','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:39','comment' => 'No comment '),
  array('dataid' => '162','userid' => '386','locx' => '21','locy' => '1570','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:58','comment' => 'No comment '),
  array('dataid' => '161','userid' => '339','locx' => '850','locy' => '997','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:24','comment' => 'Too much water'),
  array('dataid' => '160','userid' => '181','locx' => '2210','locy' => '2364','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:60','comment' => 'Too much water'),
  array('dataid' => '159','userid' => '252','locx' => '199','locy' => '1110','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:44','comment' => ' '),
  array('dataid' => '158','userid' => '44','locx' => '2442','locy' => '2045','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:18','comment' => 'No comment '),
  array('dataid' => '157','userid' => '195','locx' => '1992','locy' => '2338','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:45','comment' => ' '),
  array('dataid' => '156','userid' => '211','locx' => '2002','locy' => '2443','customdata' => '21','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:56','comment' => 'Too much water'),
  array('dataid' => '155','userid' => '361','locx' => '1375','locy' => '2085','customdata' => '12','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:34','comment' => 'Too much water'),
  array('dataid' => '154','userid' => '8','locx' => '1108','locy' => '968','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:57','comment' => ' '),
  array('dataid' => '153','userid' => '282','locx' => '728','locy' => '1013','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:19','comment' => 'Need fix now'),
  array('dataid' => '152','userid' => '73','locx' => '2370','locy' => '793','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:31','comment' => 'No comment '),
  array('dataid' => '151','userid' => '129','locx' => '692','locy' => '1068','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:51','comment' => 'No comment '),
  array('dataid' => '150','userid' => '170','locx' => '1333','locy' => '2247','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '18:36','comment' => 'Need fix now'),
  array('dataid' => '149','userid' => '303','locx' => '2411','locy' => '952','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:31','comment' => 'Need fix now'),
  array('dataid' => '148','userid' => '235','locx' => '691','locy' => '2475','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:54','comment' => 'Need fix now'),
  array('dataid' => '147','userid' => '150','locx' => '11','locy' => '1360','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:11','comment' => 'No comment '),
  array('dataid' => '146','userid' => '239','locx' => '1037','locy' => '1418','customdata' => '19','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:46','comment' => 'No comment '),
  array('dataid' => '145','userid' => '272','locx' => '2206','locy' => '293','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '6:27','comment' => ' '),
  array('dataid' => '144','userid' => '78','locx' => '1496','locy' => '2187','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:35','comment' => ' '),
  array('dataid' => '143','userid' => '257','locx' => '2028','locy' => '2286','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:23','comment' => 'Too much water'),
  array('dataid' => '142','userid' => '184','locx' => '31','locy' => '793','customdata' => '10','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:37','comment' => 'Need fix now'),
  array('dataid' => '141','userid' => '133','locx' => '676','locy' => '1210','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:8','comment' => ' '),
  array('dataid' => '140','userid' => '320','locx' => '2233','locy' => '1769','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:27','comment' => 'Need fix now'),
  array('dataid' => '139','userid' => '368','locx' => '1682','locy' => '949','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:43','comment' => 'Too much water'),
  array('dataid' => '138','userid' => '344','locx' => '2299','locy' => '615','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:31','comment' => 'Too much water'),
  array('dataid' => '137','userid' => '22','locx' => '2412','locy' => '765','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:13','comment' => 'No comment '),
  array('dataid' => '136','userid' => '296','locx' => '1289','locy' => '920','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '23:12','comment' => 'Too much water'),
  array('dataid' => '135','userid' => '227','locx' => '1182','locy' => '478','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '6:49','comment' => 'Need fix now'),
  array('dataid' => '134','userid' => '96','locx' => '1676','locy' => '1903','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:1','comment' => 'No comment '),
  array('dataid' => '133','userid' => '251','locx' => '929','locy' => '575','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:17','comment' => 'Too much water'),
  array('dataid' => '132','userid' => '144','locx' => '82','locy' => '1259','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:40','comment' => 'No comment '),
  array('dataid' => '131','userid' => '195','locx' => '1791','locy' => '2095','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '18:33','comment' => 'Too much water'),
  array('dataid' => '130','userid' => '265','locx' => '15','locy' => '847','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '10:44','comment' => 'Too much water'),
  array('dataid' => '129','userid' => '165','locx' => '847','locy' => '1288','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:55','comment' => ' '),
  array('dataid' => '128','userid' => '126','locx' => '2479','locy' => '340','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '11:54','comment' => 'Too much water'),
  array('dataid' => '127','userid' => '163','locx' => '744','locy' => '80','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:58','comment' => 'No comment '),
  array('dataid' => '126','userid' => '322','locx' => '2079','locy' => '1148','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:36','comment' => 'Too much water'),
  array('dataid' => '125','userid' => '347','locx' => '685','locy' => '802','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:19','comment' => 'Too much water'),
  array('dataid' => '124','userid' => '361','locx' => '1935','locy' => '668','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '3:21','comment' => ' '),
  array('dataid' => '123','userid' => '252','locx' => '2346','locy' => '907','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:29','comment' => 'No comment '),
  array('dataid' => '122','userid' => '316','locx' => '809','locy' => '862','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:1','comment' => ' '),
  array('dataid' => '121','userid' => '231','locx' => '657','locy' => '1968','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:19','comment' => 'Need fix now'),
  array('dataid' => '120','userid' => '347','locx' => '1206','locy' => '2472','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:23','comment' => 'No comment '),
  array('dataid' => '119','userid' => '67','locx' => '279','locy' => '2489','customdata' => '21','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:19','comment' => 'Need fix now'),
  array('dataid' => '118','userid' => '323','locx' => '1222','locy' => '141','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '8:39','comment' => 'Too much water'),
  array('dataid' => '117','userid' => '146','locx' => '2300','locy' => '1303','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '7:35','comment' => ' '),
  array('dataid' => '116','userid' => '115','locx' => '1817','locy' => '991','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '25:51','comment' => 'Too much water'),
  array('dataid' => '115','userid' => '269','locx' => '255','locy' => '1772','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:7','comment' => ' '),
  array('dataid' => '114','userid' => '303','locx' => '1672','locy' => '2231','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:16','comment' => 'No comment '),
  array('dataid' => '113','userid' => '365','locx' => '26','locy' => '236','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '20:22','comment' => 'No comment '),
  array('dataid' => '112','userid' => '222','locx' => '2259','locy' => '1677','customdata' => '7','custommode' => 'inch','approximatedata' => '1 feet','time' => '4:5','comment' => 'Too much water'),
  array('dataid' => '111','userid' => '294','locx' => '2186','locy' => '639','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:10','comment' => 'Too much water'),
  array('dataid' => '110','userid' => '154','locx' => '1895','locy' => '1984','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:8','comment' => 'No comment '),
  array('dataid' => '109','userid' => '385','locx' => '451','locy' => '800','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '18:29','comment' => ' '),
  array('dataid' => '108','userid' => '357','locx' => '908','locy' => '583','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:13','comment' => 'Too much water'),
  array('dataid' => '107','userid' => '142','locx' => '1994','locy' => '2284','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:32','comment' => 'Need fix now'),
  array('dataid' => '106','userid' => '83','locx' => '325','locy' => '840','customdata' => '16','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:9','comment' => 'Need fix now'),
  array('dataid' => '105','userid' => '265','locx' => '2447','locy' => '1379','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '11:52','comment' => ' '),
  array('dataid' => '104','userid' => '360','locx' => '1420','locy' => '1471','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:2','comment' => 'No comment '),
  array('dataid' => '103','userid' => '390','locx' => '1514','locy' => '2402','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:39','comment' => 'No comment '),
  array('dataid' => '102','userid' => '372','locx' => '1879','locy' => '1388','customdata' => '5','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:60','comment' => 'No comment '),
  array('dataid' => '101','userid' => '221','locx' => '999','locy' => '2458','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:15','comment' => ' '),
  array('dataid' => '100','userid' => '44','locx' => '1665','locy' => '1371','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '22:17','comment' => 'No comment '),
  array('dataid' => '99','userid' => '281','locx' => '2327','locy' => '1723','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:41','comment' => 'Need fix now'),
  array('dataid' => '98','userid' => '304','locx' => '2272','locy' => '2243','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:15','comment' => 'Too much water'),
  array('dataid' => '97','userid' => '354','locx' => '2200','locy' => '1660','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '3:34','comment' => 'Too much water'),
  array('dataid' => '96','userid' => '226','locx' => '1365','locy' => '1025','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:22','comment' => 'Need fix now'),
  array('dataid' => '95','userid' => '253','locx' => '2246','locy' => '1651','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:37','comment' => 'Need fix now'),
  array('dataid' => '94','userid' => '176','locx' => '1939','locy' => '2414','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:53','comment' => 'Too much water'),
  array('dataid' => '93','userid' => '273','locx' => '585','locy' => '423','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:49','comment' => 'No comment '),
  array('dataid' => '92','userid' => '185','locx' => '1035','locy' => '365','customdata' => '17','custommode' => 'inch','approximatedata' => '1 feet','time' => '8:17','comment' => 'Need fix now'),
  array('dataid' => '91','userid' => '156','locx' => '2433','locy' => '869','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:25','comment' => ' '),
  array('dataid' => '90','userid' => '254','locx' => '793','locy' => '545','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:19','comment' => 'Too much water'),
  array('dataid' => '89','userid' => '21','locx' => '1656','locy' => '700','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '26:11','comment' => 'Too much water'),
  array('dataid' => '88','userid' => '22','locx' => '2191','locy' => '1598','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:21','comment' => 'Too much water'),
  array('dataid' => '87','userid' => '238','locx' => '38','locy' => '1553','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '9:4','comment' => 'No comment '),
  array('dataid' => '86','userid' => '1','locx' => '2273','locy' => '2411','customdata' => '11','custommode' => 'inch','approximatedata' => '3 feet','time' => '20:48','comment' => 'No comment '),
  array('dataid' => '85','userid' => '73','locx' => '828','locy' => '380','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:13','comment' => 'Need fix now'),
  array('dataid' => '84','userid' => '66','locx' => '272','locy' => '1029','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '2:45','comment' => 'Too much water'),
  array('dataid' => '83','userid' => '313','locx' => '481','locy' => '374','customdata' => '8','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:6','comment' => 'No comment '),
  array('dataid' => '82','userid' => '299','locx' => '215','locy' => '2485','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '18:23','comment' => 'Too much water'),
  array('dataid' => '81','userid' => '305','locx' => '2174','locy' => '552','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '10:32','comment' => 'Need fix now'),
  array('dataid' => '80','userid' => '211','locx' => '513','locy' => '1231','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '13:24','comment' => 'Too much water'),
  array('dataid' => '79','userid' => '171','locx' => '537','locy' => '1594','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:19','comment' => 'Too much water'),
  array('dataid' => '78','userid' => '193','locx' => '1193','locy' => '723','customdata' => '21','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:22','comment' => 'Too much water'),
  array('dataid' => '77','userid' => '375','locx' => '1477','locy' => '2051','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:34','comment' => ' '),
  array('dataid' => '76','userid' => '350','locx' => '1339','locy' => '1285','customdata' => '18','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:58','comment' => ' '),
  array('dataid' => '75','userid' => '6','locx' => '2054','locy' => '1268','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:33','comment' => ' '),
  array('dataid' => '74','userid' => '154','locx' => '1600','locy' => '2007','customdata' => '16','custommode' => 'inch','approximatedata' => '1 feet','time' => '17:26','comment' => 'Too much water'),
  array('dataid' => '73','userid' => '232','locx' => '1027','locy' => '2442','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:30','comment' => 'No comment '),
  array('dataid' => '72','userid' => '76','locx' => '953','locy' => '806','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '5:14','comment' => 'Need fix now'),
  array('dataid' => '71','userid' => '78','locx' => '2365','locy' => '2365','customdata' => '6','custommode' => 'inch','approximatedata' => '3 feet','time' => '23:12','comment' => 'Too much water'),
  array('dataid' => '70','userid' => '282','locx' => '2003','locy' => '186','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '21:49','comment' => 'No comment '),
  array('dataid' => '69','userid' => '335','locx' => '1360','locy' => '2408','customdata' => '19','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:14','comment' => 'Too much water'),
  array('dataid' => '68','userid' => '27','locx' => '185','locy' => '1469','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '24:51','comment' => ' '),
  array('dataid' => '67','userid' => '143','locx' => '77','locy' => '358','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:4','comment' => 'No comment '),
  array('dataid' => '66','userid' => '208','locx' => '1982','locy' => '1467','customdata' => '5','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:24','comment' => ' '),
  array('dataid' => '65','userid' => '163','locx' => '1569','locy' => '1442','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:54','comment' => 'Need fix now'),
  array('dataid' => '64','userid' => '24','locx' => '122','locy' => '227','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:42','comment' => 'No comment '),
  array('dataid' => '63','userid' => '162','locx' => '1036','locy' => '867','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:50','comment' => 'No comment '),
  array('dataid' => '62','userid' => '157','locx' => '2366','locy' => '1082','customdata' => '18','custommode' => 'inch','approximatedata' => '1 feet','time' => '26:26','comment' => 'No comment '),
  array('dataid' => '61','userid' => '141','locx' => '1970','locy' => '2438','customdata' => '13','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:26','comment' => ' '),
  array('dataid' => '60','userid' => '314','locx' => '270','locy' => '1867','customdata' => '9','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:9','comment' => 'Need fix now'),
  array('dataid' => '59','userid' => '1','locx' => '1468','locy' => '88','customdata' => '20','custommode' => 'inch','approximatedata' => '2 feet','time' => '8:18','comment' => ' '),
  array('dataid' => '58','userid' => '263','locx' => '2434','locy' => '198','customdata' => '11','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:32','comment' => 'No comment '),
  array('dataid' => '57','userid' => '348','locx' => '40','locy' => '336','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:52','comment' => 'Need fix now'),
  array('dataid' => '56','userid' => '65','locx' => '2106','locy' => '1247','customdata' => '2','custommode' => 'inch','approximatedata' => '2 feet','time' => '4:6','comment' => 'Too much water'),
  array('dataid' => '55','userid' => '121','locx' => '135','locy' => '637','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '1:44','comment' => ' '),
  array('dataid' => '54','userid' => '366','locx' => '268','locy' => '2174','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '5:47','comment' => 'Need fix now'),
  array('dataid' => '53','userid' => '316','locx' => '1070','locy' => '1936','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '26:11','comment' => ' '),
  array('dataid' => '52','userid' => '320','locx' => '103','locy' => '1361','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '5:25','comment' => ' '),
  array('dataid' => '51','userid' => '303','locx' => '529','locy' => '2135','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:39','comment' => 'Need fix now'),
  array('dataid' => '50','userid' => '141','locx' => '770','locy' => '1406','customdata' => '16','custommode' => 'inch','approximatedata' => '2 feet','time' => '6:11','comment' => 'Too much water'),
  array('dataid' => '49','userid' => '371','locx' => '1697','locy' => '870','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:51','comment' => ' '),
  array('dataid' => '48','userid' => '23','locx' => '103','locy' => '235','customdata' => '8','custommode' => 'inch','approximatedata' => '3 feet','time' => '17:23','comment' => 'Too much water'),
  array('dataid' => '47','userid' => '182','locx' => '1553','locy' => '1934','customdata' => '5','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:42','comment' => 'No comment '),
  array('dataid' => '46','userid' => '3','locx' => '1495','locy' => '612','customdata' => '21','custommode' => 'inch','approximatedata' => '3 feet','time' => '16:8','comment' => 'No comment '),
  array('dataid' => '45','userid' => '271','locx' => '2497','locy' => '807','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:14','comment' => 'Too much water'),
  array('dataid' => '44','userid' => '373','locx' => '1924','locy' => '1824','customdata' => '21','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:15','comment' => 'Need fix now'),
  array('dataid' => '43','userid' => '192','locx' => '2178','locy' => '1528','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '26:19','comment' => 'No comment '),
  array('dataid' => '42','userid' => '387','locx' => '34','locy' => '1164','customdata' => '15','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:10','comment' => 'Need fix now'),
  array('dataid' => '41','userid' => '60','locx' => '545','locy' => '460','customdata' => '14','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:45','comment' => 'No comment '),
  array('dataid' => '40','userid' => '397','locx' => '2068','locy' => '1156','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '14:5','comment' => 'No comment '),
  array('dataid' => '39','userid' => '146','locx' => '1195','locy' => '63','customdata' => '15','custommode' => 'inch','approximatedata' => '1 feet','time' => '19:33','comment' => 'No comment '),
  array('dataid' => '38','userid' => '187','locx' => '744','locy' => '624','customdata' => '5','custommode' => 'inch','approximatedata' => '3 feet','time' => '13:32','comment' => ' '),
  array('dataid' => '37','userid' => '106','locx' => '203','locy' => '705','customdata' => '10','custommode' => 'inch','approximatedata' => '2 feet','time' => '7:27','comment' => ' '),
  array('dataid' => '36','userid' => '150','locx' => '2433','locy' => '1289','customdata' => '19','custommode' => 'inch','approximatedata' => '1 feet','time' => '22:50','comment' => 'No comment '),
  array('dataid' => '35','userid' => '61','locx' => '944','locy' => '1559','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '23:26','comment' => ' '),
  array('dataid' => '34','userid' => '369','locx' => '2164','locy' => '731','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '9:10','comment' => ' '),
  array('dataid' => '33','userid' => '158','locx' => '1692','locy' => '295','customdata' => '14','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:58','comment' => 'No comment '),
  array('dataid' => '32','userid' => '56','locx' => '1879','locy' => '371','customdata' => '5','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:10','comment' => 'No comment '),
  array('dataid' => '31','userid' => '313','locx' => '1067','locy' => '986','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '2:36','comment' => ' '),
  array('dataid' => '30','userid' => '323','locx' => '152','locy' => '1354','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '16:19','comment' => ' '),
  array('dataid' => '29','userid' => '87','locx' => '1782','locy' => '65','customdata' => '17','custommode' => 'inch','approximatedata' => '3 feet','time' => '1:23','comment' => 'No comment '),
  array('dataid' => '28','userid' => '357','locx' => '2167','locy' => '468','customdata' => '13','custommode' => 'inch','approximatedata' => '3 feet','time' => '4:29','comment' => 'Need fix now'),
  array('dataid' => '27','userid' => '293','locx' => '519','locy' => '2167','customdata' => '20','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:59','comment' => 'Need fix now'),
  array('dataid' => '26','userid' => '399','locx' => '210','locy' => '968','customdata' => '3','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:57','comment' => 'Need fix now'),
  array('dataid' => '25','userid' => '388','locx' => '705','locy' => '495','customdata' => '16','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:44','comment' => 'Too much water'),
  array('dataid' => '24','userid' => '245','locx' => '1566','locy' => '308','customdata' => '11','custommode' => 'inch','approximatedata' => '2 feet','time' => '11:29','comment' => 'Need fix now'),
  array('dataid' => '23','userid' => '252','locx' => '323','locy' => '2024','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '25:36','comment' => ' '),
  array('dataid' => '22','userid' => '208','locx' => '477','locy' => '1238','customdata' => '3','custommode' => 'inch','approximatedata' => '1 feet','time' => '1:44','comment' => 'No comment '),
  array('dataid' => '21','userid' => '339','locx' => '791','locy' => '2244','customdata' => '2','custommode' => 'inch','approximatedata' => '3 feet','time' => '24:19','comment' => ' '),
  array('dataid' => '20','userid' => '149','locx' => '846','locy' => '1884','customdata' => '21','custommode' => 'inch','approximatedata' => '1 feet','time' => '21:22','comment' => 'Too much water'),
  array('dataid' => '19','userid' => '42','locx' => '134','locy' => '547','customdata' => '4','custommode' => 'inch','approximatedata' => '3 feet','time' => '10:56','comment' => ' '),
  array('dataid' => '18','userid' => '363','locx' => '540','locy' => '1423','customdata' => '17','custommode' => 'inch','approximatedata' => '2 feet','time' => '17:12','comment' => ' '),
  array('dataid' => '17','userid' => '189','locx' => '2455','locy' => '1419','customdata' => '4','custommode' => 'inch','approximatedata' => '2 feet','time' => '9:42','comment' => 'Need fix now'),
  array('dataid' => '16','userid' => '258','locx' => '940','locy' => '1117','customdata' => '9','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:58','comment' => ' '),
  array('dataid' => '15','userid' => '351','locx' => '1165','locy' => '584','customdata' => '3','custommode' => 'inch','approximatedata' => '2 feet','time' => '15:51','comment' => 'Need fix now'),
  array('dataid' => '14','userid' => '362','locx' => '583','locy' => '107','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '15:31','comment' => ' '),
  array('dataid' => '13','userid' => '273','locx' => '1683','locy' => '2396','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '16:45','comment' => 'No comment '),
  array('dataid' => '12','userid' => '305','locx' => '1551','locy' => '2343','customdata' => '12','custommode' => 'inch','approximatedata' => '1 feet','time' => '12:19','comment' => 'Need fix now'),
  array('dataid' => '11','userid' => '339','locx' => '1954','locy' => '2449','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '14:18','comment' => 'No comment '),
  array('dataid' => '10','userid' => '167','locx' => '133','locy' => '1594','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:21','comment' => 'Too much water'),
  array('dataid' => '9','userid' => '302','locx' => '900','locy' => '1739','customdata' => '15','custommode' => 'inch','approximatedata' => '3 feet','time' => '11:7','comment' => 'No comment '),
  array('dataid' => '8','userid' => '65','locx' => '1852','locy' => '298','customdata' => '10','custommode' => 'inch','approximatedata' => '3 feet','time' => '19:3','comment' => 'No comment '),
  array('dataid' => '7','userid' => '379','locx' => '47','locy' => '369','customdata' => '18','custommode' => 'inch','approximatedata' => '3 feet','time' => '18:50','comment' => 'Need fix now'),
  array('dataid' => '6','userid' => '348','locx' => '2174','locy' => '151','customdata' => '6','custommode' => 'inch','approximatedata' => '2 feet','time' => '18:29','comment' => 'No comment '),
  array('dataid' => '5','userid' => '212','locx' => '677','locy' => '1309','customdata' => '4','custommode' => 'inch','approximatedata' => '1 feet','time' => '15:24','comment' => 'No comment '),
  array('dataid' => '4','userid' => '372','locx' => '1226','locy' => '2228','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '14:7','comment' => 'Too much water'),
  array('dataid' => '3','userid' => '154','locx' => '2337','locy' => '446','customdata' => '14','custommode' => 'inch','approximatedata' => '2 feet','time' => '19:3','comment' => 'No comment '),
  array('dataid' => '2','userid' => '362','locx' => '1974','locy' => '715','customdata' => '13','custommode' => 'inch','approximatedata' => '2 feet','time' => '12:28','comment' => 'Need fix now'),
  array('dataid' => '1','userid' => '125','locx' => '51','locy' => '977','customdata' => '20','custommode' => 'inch','approximatedata' => '1 feet','time' => '7:30','comment' => 'Need fix now')
);
